name: CI-on-pullrequest

on: [pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.10", "3.11", "3.12"]
        exclude:
          # Exclude Python 3.10 on macOS latest
          - os: "macos-latest"
            python-version: "3.10"
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install
        run: |
          pip install poetry
          poetry install --with dev,test
          
      - name: Run tests
        run: |
          poetry run pytest

      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v1
